n1 = int(input('Enter your first number:'))
n2 = int(input('Enter your second number:'))
n3 = int(input('Enter your third number:'))
list = []
list.append(n1)
list.append(n2)
list.append(n3)
print(list)
list.sort()
print(list)
